
auxTests = {'depth range test': 'OFF'}

tsQualityTests = {
             'temperature sensor range': 'ON',
             'salinity sensor range': 'OFF',
             'conductivity sensor range': 'OFF',
             'pressure sensor range': 'OFF',
             'temperature environmental range': 'ON',
             'salinity environmental range': 'OFF',
             'conductivity environmental range': 'OFF',
             'pressure environmental range': 'OFF',
             'pH environmental range': 'OFF',
             'chlorophyll environmental range': 'OFF',
             'dissolved oxygen environmental range': 'OFF',
             'dissolved organic matter environmental range': 'OFF',
             'turbidity environmental range': 'OFF',
             'temperature spikes': 'ON',
             'salinity spikes': 'OFF',
             'conductivity spikes': 'OFF',
             'pressure spikes': 'OFF',
             'pH spikes': 'OFF',
             'chlorophyll spikes': 'OFF',
             'dissolved oxygen spikes': 'OFF',
             'dissolved organic matter spikes': 'OFF',
             'turbidity spikes': 'OFF',
             'temperature rate of change': 'OFF',
             'salinity rate of change': 'OFF',
             'conductivity rate of change': 'OFF',
             'pressure rate of change': 'OFF',
             'temperature flat line': 'ON',
             'salinity flat line': 'OFF',
             'conductivity flat line': 'OFF',
             'pressure flat line': 'OFF',
             'temperature vertical gradient': 'OFF',
             'salinity vertical gradient': 'OFF',
             'conductivity vertical gradient': 'OFF'
             }

tsSettings = {
                'depth_range': 1.55,
                'sensor_min_temp': -5,
                'sensor_max_temp': 35,
                'sensor_min_sal': 2,
                'sensor_max_sal': 42,
                'sensor_min_cond': 0,
                'sensor_max_cond': 70,
                'sensor_min_pres': 0,
                'sensor_max_pres':10050,

                'env_min_temp': 15,
                'env_max_temp': 35,
                'env_min_sal': 34,
                'env_max_sal': 38,
                'env_min_cond': 20,
                'env_max_cond': 70,
                'env_min_pres': 10,
                'env_max_pres': 300,
                'env_min_pH': 8,
                'env_max_pH': 8.5,
                'env_min_chl': 0.01,
                'env_max_chl': 4.5,
                'env_min_O2': 190,
                'env_max_O2': 300,
                'env_min_org': 0,
                'env_max_org': 10,
                'env_min_tur': 0,
                'env_max_tur': 20,

                'rep_cnt_fail': 20,
                'rep_cnt_susp': 15,
                'eps': 0.00001,

                'time_window': 'WHOLE',
                'fail_factor': 3,
                'susp_factor': 2.5,
                }
